from __future__ import annotations
import hashlib, subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'V24-I11-V6-RQ1-RQ16-PREREGISTRATION-REVIEW.md'
FILES=[ROOT/'implementation/v24/V24-I11-V6-RQ1-RQ16-PREREGISTRATION.md',ROOT/'implementation/v24/V24-I11-V6-RQ1-RQ16-EXECUTION-CONTRACT.json',ROOT/'implementation/v24/V24-I11-V6-RQ1-RQ16-CLEANUP-CONTRACT.md',ROOT/'implementation/v24/V24-I11-V6-RQ1-RQ16-PREREGISTRATION-ISSUES.json',ROOT/'implementation/v24/V24-I11-V6-RQ1-RQ16-AUTHORIZATION-TOKEN-SCHEMA.json',ROOT/'implementation/v24/V24-I11-V6-RQ1-RQ16-READONLY-CAPABILITY-INSPECTION.md',ROOT/'governance-runtime/v24_v6_rq1_rq16_harness.py',ROOT/'governance-runtime/test_v24_v6_rq1_rq16_harness.py',ROOT/'governance-runtime/run_v24_v6_rq1_rq16_mutations.py',ROOT/'governance-runtime/check_rq16_preregistration_packet.py']
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def run(cmd): return subprocess.run(cmd,cwd=ROOT,text=True,capture_output=True)
def fence(name,body,lang='text'): return f'\n### {name}\n\n```{lang}\n{body.rstrip()}\n```\n'
def main():
    tests=run(['python','governance-runtime/test_v24_v6_rq1_rq16_harness.py']); selftest=run(['python','governance-runtime/v24_v6_rq1_rq16_harness.py','--self-test']); plan=run(['python','governance-runtime/v24_v6_rq1_rq16_harness.py','--plan']); refuse=run(['python','governance-runtime/v24_v6_rq1_rq16_harness.py','--execute-rq16']); mutations=run(['python','governance-runtime/run_v24_v6_rq1_rq16_mutations.py']); consistency=run(['python','governance-runtime/check_rq16_preregistration_packet.py'])
    diff=run(['git','diff','8477830f5f35a35a8c9b19fdca9c5b6c39e2916d','HEAD']).stdout
    parts=['# V24-I11-V6 RQ-16 preregistration review','','Planning-only artifact. No RQ-16 execution occurred.','','## Identity','predecessor_commit=8477830f5f35a35a8c9b19fdca9c5b6c39e2916d','predecessor_tree=82457b9307f133db281055dbbdae26b618f8c3cf',f"branch={run(['git','branch','--show-current']).stdout.strip()}",f"head={run(['git','rev-parse','HEAD']).stdout.strip()}",f"tree={run(['git','rev-parse','HEAD^{tree}']).stdout.strip()}",'RQ16_EXECUTED=false','RQ16_AUTHORIZED=false','RQ16_started=false','scientific_rerun=false','qualification=NOT_QUALIFIED','scientific_execution_state=CLOSED_PENDING_SUCCESSOR_REVIEW','authority_effect=NONE_EVIDENCE_ONLY','', '## Frozen contract', fence('execution contract',FILES[1].read_text(),'json'), '## Source-path analysis', fence('preregistration',FILES[0].read_text(),'markdown'), '## Cleanup contract', fence('cleanup',FILES[2].read_text(),'markdown'), '## Issues', fence('issue ledger',FILES[3].read_text(),'json')]
    parts.append('## Included file SHA-256\n' + '\n'.join(f'{sha(p)}  {p.relative_to(ROOT).as_posix()}' for p in FILES))
    for p in FILES[4:]: parts.append(fence(p.relative_to(ROOT).as_posix()+f' sha256={sha(p)}',p.read_text(),'python'))
    compile_result=run(['python','-m','compileall','-q']+[str(p) for p in FILES[4:]])
    parts += ['## Static results', fence('plan output',plan.stdout+plan.stderr),fence('self-test output',selftest.stdout+selftest.stderr),fence('unit output',tests.stdout+tests.stderr),fence('mutation output',mutations.stdout+mutations.stderr,'json'),fence('packet consistency',consistency.stdout+consistency.stderr),fence('execution refusal output',refuse.stdout+refuse.stderr),f'compile_exit={compile_result.returncode}', '## Exact diff from predecessor', fence('git diff',diff), '## Manual-review questions','','Determine independently whether each arm has a safe literal bound-runtime mechanism without changing the frozen oracle or colliding with RQ-17. Adjudicate the insufficient/unsafe classifications for ENOSPC, EROFS, EIO and EACCES. Do not authorize execution or RQ-16.']
    OUT.write_text('\n'.join(parts)+'\n',encoding='utf-8'); print(OUT)
if __name__=='__main__': main()
